# Generated by Django 4.2.5 on 2023-10-13 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adress',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='telefone',
            new_name='phone_number',
        ),
    ]
