# Generated by Django 4.2.5 on 2023-10-03 11:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='num_stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.validate_integer], verbose_name='quantity in stock'),
        ),
    ]
